name: simproktools
description: A library with a range of useful machines for simprokmachine framework.
version: 1.1.2
homepage: https://github.com/simprok-dev/simproktools-flutter
documentation: https://github.com/simprok-dev/simproktools-flutter

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  simprokmachine: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
